// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AcordController from "./acord_controller"
application.register("acord", AcordController)

import EtapasvalpyController from "./etapasvalpy_controller"
application.register("etapasvalpy", EtapasvalpyController)

import FuenteController from "./fuente_controller"
application.register("fuente", FuenteController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import InstitucionController from "./institucion_controller"
application.register("institucion", InstitucionController)

import MenupController from "./menup_controller"
application.register("menup", MenupController)

import MenuseccController from "./menusecc_controller"
application.register("menusecc", MenuseccController)

import NestedFormEstController from "./nested_form_est_controller"
application.register("nested-form-est", NestedFormEstController)

import NestedFormFconController from "./nested_form_fcon_controller"
application.register("nested-form-fcon", NestedFormFconController)

import NestedFormFespController from "./nested_form_fesp_controller"
application.register("nested-form-fesp", NestedFormFespController)

import NestedFormFfisController from "./nested_form_ffis_controller"
application.register("nested-form-ffis", NestedFormFfisController)

import NestedFormFondoController from "./nested_form_fondo_controller"
application.register("nested-form-fondo", NestedFormFondoController)

import NestedFormInstController from "./nested_form_inst_controller"
application.register("nested-form-inst", NestedFormInstController)

import NestedFormInvController from "./nested_form_inv_controller"
application.register("nested-form-inv", NestedFormInvController)

import NestedFormSolController from "./nested_form_sol_controller"
application.register("nested-form-sol", NestedFormSolController)

import NestedFormTecController from "./nested_form_tec_controller"
application.register("nested-form-tec", NestedFormTecController)

import NotificaController from "./notifica_controller"
application.register("notifica", NotificaController)

import ParticipanController from "./participan_controller"
application.register("participan", ParticipanController)

import PresupSolController from "./presup_sol_controller"
application.register("presup-sol", PresupSolController)

import ProyectoController from "./proyecto_controller"
application.register("proyecto", ProyectoController)

import SlimController from "./slim_controller"
application.register("slim", SlimController)

import TabsprController from "./tabspr_controller"
application.register("tabspr", TabsprController)

import TabsrecController from "./tabsrec_controller"
application.register("tabsrec", TabsrecController)

import TooltipController from "./tooltip_controller"
application.register("tooltip", TooltipController)

import TrixController from "./trix_controller"
application.register("trix", TrixController)

import UploadfileController from "./uploadfile_controller"
application.register("uploadfile", UploadfileController)

import UpsfController from "./upsf_controller"
application.register("upsf", UpsfController)

import UtilsController from "./utils_controller"
application.register("utils", UtilsController)
